services:
  app:
    build:
      context: .
    image: bi-demo-image
    container_name: bi-demo-container
    env_file:
      - ./backend/.env
      - ./frontend/.env
      - ./.env
    ports:
      - '${PORT}:${PORT}'
